apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: nvsentinel
spec:
  type: ClusterIP
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: http
      port: 3200
      targetPort: 3200
  selector:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo